#!/usr/bin/env python3
"""Stamp review-room/STATE.md's AUTO block with the latest render's facts.

Keeps the technical half of STATE.md self-maintaining: run this after any render
(the assembler calls it; you can also run it by hand). It only rewrites the
content between the AUTO:BEGIN/AUTO:END markers, so the hand-kept Decisions/Next
block is never touched.

    python3 scripts/stamp_state.py <output.mp4> [assembler_script_path]
"""
import datetime
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "review-room" / "STATE.md"


def _probe(path, entries, sep="x"):
    try:
        o = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0",
             "-show_entries", entries, "-of", f"csv=p=0:s={sep}", str(path)],
            capture_output=True, text=True, check=True)
        return o.stdout.strip()
    except Exception:
        return "?"


def _dur(path):
    try:
        o = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
            capture_output=True, text=True, check=True)
        return f"{float(o.stdout.strip()):.0f}s"
    except Exception:
        return "?"


def _rel(p):
    p = Path(p)
    try:
        return p.resolve().relative_to(ROOT)
    except Exception:
        return p


def main():
    if not STATE.exists():
        print("STATE.md not found; skipping stamp")
        return
    out = Path(sys.argv[1]).resolve()
    script = sys.argv[2] if len(sys.argv) > 2 else "scripts/review_room_surprise.py"
    srt = out.with_suffix(".srt")
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    block = (
        "<!-- AUTO:BEGIN (regenerated by the assembler — do not hand-edit) -->\n"
        f"- **Latest render:** `{_rel(out)}` · ~{_dur(out)} · {_probe(out, 'stream=width,height')}\n"
        f"- **Captions:** `{_rel(srt)}`\n"
        f"- **Assembler:** `{script}`\n"
        f"- **Last stamped:** {ts}\n"
        "<!-- AUTO:END -->"
    )
    text = STATE.read_text()
    new = re.sub(r"<!-- AUTO:BEGIN.*?AUTO:END -->", block, text, flags=re.S)
    STATE.write_text(new)
    print("stamped STATE.md ->", _rel(out))


if __name__ == "__main__":
    main()
